# 开发环境

server:
  port: 8081

# 配置数据库
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver


  # 解决 springboot 和 swagger2 版本兼容问题
  mvc:
    pathmatch:
      # 匹配路径 Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher

  # 文件配置
  servlet:
    multipart:
      max-file-size: 10MB # 最大支持上传文件大小为 10MB
      max-request-size: 15MB # 最大请求大小为 15MB

# 打印日志到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml



address:
  maxCount: 20
swagger:
  is:
    enable: true